### PR TITLE
Fix dob date picker increasing selected date by a month

### PR DESCRIPTION
**Pull request by makombe**
## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Screenshots
[Screencast from 16-07-2024 05:56:02 ALASIRI.webm](https://github.com/user-attachments/assets/8f2f8b9a-e605-4447-9872-10ea588fb5f5)

### CODE REVIEW

**Comment by ojwanganto** [comment]
Thanks, @makombe. Kindly attach a video to help with the review.

**Comment by makombe** [comment]
> Thanks, @makombe. Kindly attach a video to help with the review.

Please check added. Thanks

**Comment by ojwanganto** [comment]
@makombe - please link this to a ticket for the issue. Please also remember to push this to the community. Did you check that the date picker in the community repo is broken?

**Comment by makombe** [comment]
The community one is ok. That change is already available in the community

**Pull request merged**
