### PR TITLE
Patient identifier mapping to fields now working

### PR DESCRIPTION
**Pull request by munania**
## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

### CODE REVIEW

**Comment by munania** [comment]
https://github.com/palladiumkenya/openmrs-esm-patient-management/assets/35590825/0bbb2692-d1dc-4ca8-9551-778859db2cc3

**Review by donaldkibet — APPROVED** [review]
LGTM Thanks @munania

**Review by munania — COMMENTED** [review]
Removed brackets

**Review by ojwanganto — APPROVED** [review]
LGTM

**Comment by ojwanganto** [comment]
cc @donaldkibet

**Review by donaldkibet — APPROVED** [review]
Thanks @munania LGTM

**Pull request merged**
